exploration_safety_area:
  enabled: True

  # WIDE WORLD 1
  # x_min: -50
  # x_max: 5
  # y_min: -25
  # y_max: 25
  # z_min: -1
  # z_max: 8

  # CRANE WORLD 
  x_min: -60
  x_max: 12
  # y_min: -35
  y_min: -40
  y_max: 30
  z_min: 0
  z_max: 7

# [INFO] [1743583773.635548, 14768.860000]: Sent goal: (-6.92, -22.33, 1.64)

  # TOWERS WORLD 
  # x_min: -80
  # x_max: 5
  # # y_min: -35
  # y_min: -40
  # y_max: 15
  # z_min: -1
  # z_max: 50

  # GARAGE 2
  # x_min: -80
  # x_max: 30
  # y_min: -5
  # y_max: 25
  # z_min: -1
  # z_max: 7

  # GARAGE INSIDE
  # x_min: -80
  # x_max: -10
  # y_min: -5
  # y_max: 10
  # z_min: -1
  # z_max: 6
